### ISSUE TITLE
How test this in Emulator ?

### ISSUE THREAD

**Issue by hadifar** [MultiScreenSDK/sample-trailmix-android#1]
Hi , I'm fairly new to this SDK , I wanna run and test this library but I cant run emulator ? could you please help me to run this in emulator ? I stuck on this two days :(

**Comment by sunilr1** [comment]
Hi Amir

Unfortunately there is an issue with Tizen emulator that prevents it from being used for Multiscreen app development. We are working on a fix. Meanwhile the best way to run the sample apps is on a real Samsung 2015 TV that supports Multiscreen service. You can read how to and the TV models that support it here - https://github.com/MultiScreenSDK/multiscreen-guide.

Hope that helps.

Regards
Sunil
